artifact_uri: /workspaces/mlops-zoomcamp/02-experiment-tracking/homework/sqlite/mlflow.db/0/9d36a836d25847bc9c7c2a0d473f6726/artifacts
end_time: 1717363788119
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 9d36a836d25847bc9c7c2a0d473f6726
run_name: burly-robin-834
run_uuid: 9d36a836d25847bc9c7c2a0d473f6726
source_name: ''
source_type: 4
source_version: ''
start_time: 1717363780961
status: 4
tags: []
user_id: codespace
