artifact_uri: /workspaces/mlops-zoomcamp/02-experiment-tracking/homework/sqlite/mlflow.db/759579995062249526/ebe397fb9c9d402cbea4cfc7475681ba/artifacts
end_time: 1717363788118
entry_point_name: ''
experiment_id: '759579995062249526'
lifecycle_stage: active
run_id: ebe397fb9c9d402cbea4cfc7475681ba
run_name: victorious-doe-797
run_uuid: ebe397fb9c9d402cbea4cfc7475681ba
source_name: ''
source_type: 4
source_version: ''
start_time: 1717363780995
status: 4
tags: []
user_id: codespace
